### ISSUE TITLE
Start Databricks cluster in Lab 1

### ISSUE THREAD

**Issue by GraemeMalcolm** [ctesta-oneillmsft/xyz#10]
# Module: 01

Need an instruction to start the Databricks cluster

(unless we go with the scripted install, in which case instructions to *create* the cluster should go here.)

Also need a step to terminate it at the end of the lab

**Comment by vasuja515** [comment]
Some quota limitation issues when deploying cluster across regions. We reset the cluster to min 1 to max 4 nodes and was able to deploy the cluster.

**Comment by GraemeMalcolm** [comment]
Can we just specify a single-node cluster? (which would minimize costs as well)

**Comment by ctesta-oneillmsft** [comment]
we tried with a lower node and think have it balanced between performance and cost. Of course trainers will have to be flexible if there are region limitations.

resolved the logged issue of the termination statement
