### ISSUE TITLE
Module 4 - Explore, transform, and load data into the Data Warehouse using Apache Spark - Add instructions in Exercise 0

### ISSUE THREAD

**Issue by annav88** [ctesta-oneillmsft/xyz#12]
# Module: 4
#### Step: 7

Description of issue

If the dedicated SQL pool has still not been created, we need to specify that the students should not run the configuration PS script in step 7, as they will receive an error saying that the server could not be found. Please see the screenshot demonstrating it.

![lab4_ex0_task0_point7](https://user-images.githubusercontent.com/83666021/124642435-21e14380-de90-11eb-9ffe-2d63383004ea.png)

Thanks,
Anna

**Comment by ctesta-oneillmsft** [comment]
@annav88 It is called out in bold
![image1](https://user-images.githubusercontent.com/33545180/124645101-eee88100-de8a-11eb-8f01-ea945938f548.png)
