### ISSUE TITLE
Lab 2, Task 2, Step 2, wrong file name should be:  sale-small-20191231-snappy.parquet file

### ISSUE THREAD

**Issue by TammySmithMCT** [ctesta-oneillmsft/xyz#13]
# Module: 02
#### Step: 02

wrong file name; replace **20190101** with **20191231**

Select the Linked tab (1) and expand Azure Data Lake Storage Gen2. Expand the asaworkspaceXX primary ADLS Gen2 account (2) and select the wwi-02 container (3). Navigate to the sale-small/Year=2019/Quarter=Q4/Month=12/Day=20191231 folder (4). Right-click on the sale-small-**20190101**-snappy.parquet file (5), select New SQL script (6), then Create external table (7).

should be:  
Select the Linked tab (1) and expand Azure Data Lake Storage Gen2. Expand the asaworkspaceXX primary ADLS Gen2 account (2) and select the wwi-02 container (3). Navigate to the sale-small/Year=2019/Quarter=Q4/Month=12/Day=20191231 folder (4). Right-click on the sale-small-**20191231**-snappy.parquet file (5), select New SQL script (6), then Create external table (7).

Repro steps:

![mod2-lab2-task2-step2 wrong file name](https://user-images.githubusercontent.com/11367710/124658011-3f52e500-de71-11eb-9931-9254c3e4cf00.PNG)

**Comment by ctesta-oneillmsft** [comment]
resolved
