### ISSUE TITLE
Instructions indicate the use of Azure Data explorer, where we don't really use it in the lab

### ISSUE THREAD

**Issue by saramashfej** [ctesta-oneillmsft/xyz#14]
# Module: 01
#### Step: 00

Description of issue
The first piece of instruction in Module 1 Lab 2, indicates: 
This lab demonstrates the experience of working with Apache Spark in Azure Synapse Analytics. You will learn how to connect an Azure Synapse Analytics workspace to an Azure Data Explorer workspace using a Linked Service and then load data from one of its databases using a Spark notebook.

We don't really use Azure Data explorer or have it in any of the labs, so we may need to remove that piece.
Repro steps:

1.
1.
1.

**Comment by ctesta-oneillmsft** [comment]
resolved
