### ISSUE TITLE
Module 2 - Run interactive queries using serverless SQL pools - Exercise 1 - Task 2 - UTF8 error in the external table creation script

### ISSUE THREAD

**Issue by annav88** [ctesta-oneillmsft/xyz#15]
# Module: 2 - Run interactive queries using serverless SQL pools
#### Step: 5 - Run the script

**Description of issue**

When using the default **external table creation** script, I get an error **_"Potential conversion error while reading VARCHAR column 'TransactionId' from UTF8 encoded text. Change database collation to a UTF8 collation or specify explicit column schema in WITH clause and assign UTF8 collation to VARCHAR columns."_**

**Solution**

Using the **COLLATE Latin1_General_100_BIN2_UTF8** in the external table creation VARCHAR fields resolved the issue.

Please see the screenshots showing before/after **COLLATE Latin1_General_100_BIN2_UTF8** statement.

![lab2_ex1_task_2_point5](https://user-images.githubusercontent.com/83666021/124743320-eab97380-df1d-11eb-990f-dbc434b57c3e.png)
![lab2_ex1_task_2_point5_collate_solution](https://user-images.githubusercontent.com/83666021/124743331-ee4cfa80-df1d-11eb-8caa-b6619b17eb36.png)

Thank you,
Anna

**Comment by ctesta-oneillmsft** [comment]
This is a bug that has appeared in the last 72 hours and reported to the PG. I have repo'd it again this morning and the bug appears to have gone. PLease can you validate, as the test on my side no longer adds COLLATE in the script,or raising the error when I repeat the steps

**Comment by annav88** [comment]
Hello Chris! I still had the bug, I reproduced the steps by creating a new external table, and it is there unless if I use the COLLATION. I sent you a video by email where I demonstrate it.

Thank you,
Anna

**Comment by ctesta-oneillmsft** [comment]
SO it appears that this message is occurring on first execution of this command. Do you concur?

**Comment by annav88** [comment]
In my case it appears always unless if I use the COLLATE statement next to the VARCHAR field declaration.

**Comment by ctesta-oneillmsft** [comment]
I am still unable to repro the issue you are seeing, but I have added instructions to deal with this should it occur for student
