### ISSUE TITLE
Module 7 - Typo in Exercise 1 introduction

### ISSUE THREAD

**Issue by annav88** [ctesta-oneillmsft/xyz#16]
# Module: 7
#### Step: 00

Description of issue

In the introduction we say that the students need to fulfill the exercise if they have not completed Module 8. It should say Module 6 as the artifacts mentioned were created in Module 6 of the new version of DP203 training.

Please see the screenshot attached.

![lab7_exercise1_introduction](https://user-images.githubusercontent.com/83666021/124762731-82758c80-df33-11eb-8f3c-43713054f0a2.png)

Thank you,
Anna

**Comment by ctesta-oneillmsft** [comment]
resolved
