### ISSUE TITLE
"Potential conversion error" when creating view from CSV file

### ISSUE THREAD

**Issue by sthoward0914** [ctesta-oneillmsft/xyz#18]
# Module: 02
#### Step: 04

Description of issue

The script as it is written in the instructions uses VARCHAR data types, but this will cause this error when trying to create the view:

Potential conversion error while reading VARCHAR column 'UserName' from UTF8 encoded text. Change database collation to a UTF8 collation or specify explicit column schema in WITH clause and assign UTF8 collation to VARCHAR columns. Potential conversion error while reading VARCHAR column 'Gender' from UTF8 encoded text. Change database collation to a UTF8 collation or specify explicit column schema in WITH clause and assign UTF8 collation to VARCHAR columns. Potential conversion error while reading VARCHAR column 'Phone' from UTF8 encoded text. Change database collation to a UTF8 collation or specify explicit column schema in WITH clause and assign UTF8 collation to VARCHAR columns. Potential conversion error while reading VARCHAR column 'Email' from UTF8 encoded text. Change database collation to a UTF8 collation or specify explicit column schema in WITH clause and assign UTF8 collation to VARCHAR columns. Potential conversion error while reading VARCHAR column 'CreditCard' from UTF8 encoded text. Change database collation to a UTF8 collation or specify explicit column schema in WITH clause and assign UTF8 collation to VARCHAR columns. 

The fix is simple. Just change the VARCHAR columns to NVARCHAR columns so the script would read:

CREATE VIEW CustomerInfo AS
    SELECT * 
FROM OPENROWSET(
        BULK 'https://asadatalakeslh20210706.dfs.core.windows.net/wwi-02/customer-info/customerinfo.csv',
        FORMAT = 'CSV',
        PARSER_VERSION='2.0',
        FIRSTROW=2
    )
WITH (
    [UserName] NVARCHAR (50),
    [Gender] NVARCHAR (10),
    [Phone] NVARCHAR (50),
    [Email] NVARCHAR (100),
    [CreditCard] NVARCHAR (50)
) AS [r];
GO

SELECT * FROM CustomerInfo;
GO

The script written like this will execute without error

Repro
1. Go through steps in the lab to the indicated step

**Comment by ctesta-oneillmsft** [comment]
The bug appears to relate to:

Module 2, exercise 1, Task 3, step 4

This is the instruction

![image1](https://user-images.githubusercontent.com/33545180/124891608-0c276780-dfd1-11eb-939e-000cbbda7dc1.png)

please advise which step you are referring too

**Comment by sthoward0914** [comment]
It is task 4, step 4. This instruction:

[snip]
Update the script with the following and make sure you replace YOUR_DATALAKE_NAME (1) (your primary data lake storage account) in the OPENROWSET BULK path with the value in the in the previous select statement. Set the Use database value to demo (2) (use the refresh button to the right if needed):

sql
CREATE VIEW CustomerInfo AS
    SELECT * 
FROM OPENROWSET(
        BULK 'https://YOUR_DATALAKE_NAME.dfs.core.windows.net/wwi-02/customer-info/customerinfo.csv',
        FORMAT = 'CSV',
        PARSER_VERSION='2.0',
        FIRSTROW=2
    )
WITH (
    [UserName] VARCHAR (50),
    [Gender] VARCHAR (10),
    [Phone] VARCHAR (50),
    [Email] VARCHAR (100),
    [CreditCard] VARCHAR (50)
) AS [r];
GO

SELECT * FROM CustomerInfo;
GO
[/snip]

Sorry, I put the wrong task first time. I edited it to correct that now.

**Comment by ctesta-oneillmsft** [comment]
Thanks. Resolved
