### ISSUE TITLE
Module 00 Deployment Script

### ISSUE THREAD

**Issue by vasuja515** [ctesta-oneillmsft/xyz#22]
In the ARM template we deploy app insights, is this necessary? Also, is there a way to opt into the free tier discount for Cosmos to save costs as we are using an Azure Pass Subscription within the ARM template?

**Comment by ctesta-oneillmsft** [comment]
After a discussion with the team, we are removing app insights. However we are keeping the cosmos DB as is as there is only one free tier allowed per tennant and it is fixed at 400 RU's. We will implement the fix today
