### ISSUE TITLE
Module 2 Hyperspace

### ISSUE THREAD

**Issue by vasuja515** [ctesta-oneillmsft/xyz#23]
Working with Hyperspace should have some extra key points, and to talk about its impact. We walk through showing the different in physical plans and with and without indexes but no impact of the indexes are really demonstrated. As we are not working with large datasets yet, maybe having a note on when hyperspace makes a difference, ~how much data. Currently we're showing a difference of just a few seconds when using Hyperspace.

-Do we have some type of demo we can show the impact of using Hyperspace?

Maybe even a good link to include? Azure Synapse Analytics Hyperspace for Spark Indexing (mssqltips.com) https://www.mssqltips.com/sqlservertip/6711/azure-synapse-analytics-hyperspace-for-spark-indexing/

**Comment by ctesta-oneillmsft** [comment]
the data set is scaled down so much from the original version that the impact has been lost. so we can only show how to implement Hyperspace.
