### ISSUE TITLE
Module 1: Lab 1: Task 2: 1-Delta-Architecture notebook: Cmd 31

### ISSUE THREAD

**Issue by chris-utter** [ctesta-oneillmsft/xyz#24]
Very confusing. 

1. I assume that "Instead, we'll define a temp table based....  referes to Cmd 31 and 32, but not sure.
2. It does not appear that a materialized view is ever created.
3. Even though there is a large image of a configured live bar chart, there are no instructions on how or where to create one. No instructions on what to do with this information.
4. Cmd 30 references calling display on a streaming DataFrame, but display is not used in the preceding or following cells.

**Comment by ctesta-oneillmsft** [comment]
referring to the points raised

1. Cell 31 is where the temp table is created against the silver data.
2. The materialized view is in cell cmd 25 and we have added a note in cell cmd 24 to call that out explicitly
3. We have added a qualifying statment in cell cmd 30 to tell the students where to start plotting the chart, and the information does give them what they need
4. We have added an explicit line in cell cmd 30 to make it clear that In this case, "we are executing a SQL query on a streaming view."
