### ISSUE TITLE
Module 1: Lab 1: Task 2: 1-Delta-Architecture notebook: Cmd 33: Batch Load Data into Bronze Table

### ISSUE THREAD

**Issue by chris-utter** [ctesta-oneillmsft/xyz#25]
Separate checkpoints for each source is required when introducing new sources to a delta lake, even when the same directory is used, but no new checkpoint location is introduced here.

**Comment by ctesta-oneillmsft** [comment]
I think that the seperate checkpoints have been set after the cell cmd 4 sets the paths. Here are the checkpoints we have

1. cell cmd 12 set the bronze checkpoint location

2. cell cmd 19 set the silver checkpoint location

3. cell cmd 25 cell set the groupedCountCheckpoint checkpoint location
