### ISSUE TITLE
Module 9 - Real-time stream processing with Stream Analytics - Exercise 1 - Task 1 - Typo in instructions' Resource Group name

### ISSUE THREAD

**Issue by annav88** [ctesta-oneillmsft/xyz#28]
# Module: 9 - Real-time stream processing with Stream Analytics
#### Step: 2

Description of issue

In the description the resource group name should be **data-engineering-synapse** and not **ms-dataengineering-14**

Please see the screenshot below.

![lab_9_ex1_task1_point2](https://user-images.githubusercontent.com/83666021/124893421-00d93980-dfdb-11eb-8b7c-2239802b6190.png)

Thank you!
Anna

**Comment by annav88** [comment]
Also in Exercise 1, Task 2 Step 2

![lab9_ex1_task2_point2](https://user-images.githubusercontent.com/83666021/124894746-37fc1a80-dfdc-11eb-9b4c-a251d2b5ed23.png)

**Comment by ctesta-oneillmsft** [comment]
resolved
