### ISSUE TITLE
Module 11 - Create a stream processing solution with Event Hubs and Azure Databricks - Exercise 0 - Intro - Namespace sample name already exists

### ISSUE THREAD

**Issue by annav88** [ctesta-oneillmsft/xyz#30]
# Module: 11
#### Step: 0

Description of issue

The suggested sample name already exists, not sure though if it is because in my case the namespace name is not globally unique. Please see the screenshot attached.

![lab11_ex0_intro](https://user-images.githubusercontent.com/83666021/124922952-4822f280-dffa-11eb-9f6f-18b6559af3dd.png)

Thank you,
Anna

**Comment by ctesta-oneillmsft** [comment]
resolved
