### ISSUE TITLE
Deployment script alternative

### ISSUE THREAD

**Issue by vasuja515** [ctesta-oneillmsft/xyz#32]
If a few resources fail to deploy we should have a step by step document for folks to use if they are unable to use the deployment script in Mod 00. Similar to this https://github.com/MicrosoftLearning/AI-100-Design-Implement-Azure-AISol/blob/master/Lab1-Technical_Requirements/02-Technical_Requirements.md

This will help the students ensure they are able to provision those one off resources with the correct naming across the labs as we use other powershell cmds to load data, etc.

**Comment by ctesta-oneillmsft** [comment]
we were asked to move from a step by step setup to a scripted deployment that minimizes manual steps. As a result the setup is by design.
