### ISSUE TITLE
Mod 09 Ex 02 Task 2  #3

### ISSUE THREAD

**Issue by vasuja515** [ctesta-oneillmsft/xyz#33]
UI is updated for specifying throughput. We need to check the box which says "provision throughput for this container"

![Capture](https://user-images.githubusercontent.com/77507719/124967385-5a009780-dff2-11eb-88b3-1a2c444631a2.JPG)

**Comment by vasuja515** [comment]
Directly below this screenshot we have "here we set the partition key value to customerId, because it is a field we use most often in queries and contains a relatively high cardinality (number of unique values) for good partitioning performance. We set the throughput to Autoscale with a maximum value of 4,000 request units (RUs). This means that the container will have a minimum of 400 RUs allocated (10% of the maximum number), and will scale up to a maximum of 4,000 when the scale engine detects a high enough demand to warrant increasing the throughput. Finally, we enable the analytical store on the container, which allows us to take full advantage of the Hybrid Transactional/Analytical Processing (HTAP) architecture from within Synapse Analytics."

The partition key value is userId, in the description above we mention the key value is customerId

**Comment by ctesta-oneillmsft** [comment]
customerId changed to userId in the text. I am not seeing the UI that you are seeing, as per the image so no change there

![image1](https://user-images.githubusercontent.com/33545180/124996635-33b61880-e041-11eb-91b5-80d6ae386871.png)
