### ISSUE TITLE
Module #6 Exercise 2, Task 2, Step #7 Screenshot doesn't match code for Data flow

### ISSUE THREAD

**Issue by saramashfej** [ctesta-oneillmsft/xyz#34]
# Module: 06
#### Step: 07

Description of issue

When create the mapping columns for the data flow, the screenshot doesn't exactly match the code that we need the learners to copy over, one of them will need to be updated. 
![image](https://user-images.githubusercontent.com/10104033/124973763-f5e1d180-dff9-11eb-9f47-f6a9497cd0bb.png)

Repro steps:

1.
1.
1.

**Comment by ctesta-oneillmsft** [comment]
resolved
