### ISSUE TITLE
Overall DP-203 Feedback

### ISSUE THREAD

**Issue by vasuja515** [ctesta-oneillmsft/xyz#37]
Module 00 Deployment script
-Add additional insight on when a student has multiple Azure Pass Subscriptions
-Having a walkthrough doc of all of the resources which are created in the deployment script, from naming, passwords, usernames, containers, database ids, partition keys, user roles, etc
	- This will help students who are not as experienced in Azure and if one of the resources fail to deploy we can point the student over to the doc to create the 1 or 2 resources from scratch
-Spot instances for Databricks failed in a few regions, are we able to not use spot instances? Will this cut into costs significantly? 

Lab 1
Sequencing is a bit confusing with going directly into streaming in this module. We understand talking about the benefits of delta lake, but we will need to talk about streaming first. 
	• Cannot create a delta lake outside of Databricks
	• Synapse supports Spark 3.0 which support delta lake, but we cannot create a delta lake within synapse. 
So we need to have a better together story?

Lab 6 and 7 are fairly similar 
Is there way to include a case study, or the star schema lab (this had some SQL DB in it), PBI lab, or AML lab? And cut out 6. Lab 6 is fairly long with the main objective which is working with Synapse Pipelines. Lab 7 goes into also working with Synapse Pipelines but also using Synapse Notebooks, seems a bit redundant after going through Lab 6 then into Lab 7.

What we can replace the time for Lab 6 with (some thoughts):
-If its someone's first time in data, having a case study will help put the resources together for a cohesive story
	*case studies eased the pressure on learners to absorb the material at the design level
-Bring some key points or summary slide for optimization (lab 10 from DP203) into powerpoints or back into labs (this was on the exam)
-Customer feedback of fav labs: Module 8 (which is now Lab 7), and Module 14 (which is now Lab 10)
-Agree with the labs currently in the restructure 

Are we able to rearrange the modules to go from ingestion, store, prep, transform, visualize
Its difficult to bring the modules together

**Comment by ctesta-oneillmsft** [comment]
feedback noted
