### ISSUE TITLE
Module 8 Slides: End to end security Slide 6

### ISSUE THREAD

**Issue by saramashfej** [ctesta-oneillmsft/xyz#40]
# Module: 00
#### Step: 00

Description of issue
Can we please replace Network Security Groups and DDoS in this slide with Azure Synapse Managed Vnet and Private link? There isn't a lot of mention for those in the content or the labs so they seem a bit irrelevant especially that we are mainly dealing with PaaS  offerings where those are built into the technology. 

Repro steps:

1.
1.
1.

**Comment by ctesta-oneillmsft** [comment]
after deliberation, this will not be updated
