### ISSUE TITLE
Slides [new version of DP-203] - Module 3 typos

### ISSUE THREAD

**Issue by annav88** [ctesta-oneillmsft/xyz#41]
# Module: 03
#### Step: 00

Description of issue

Module 3 slides 4, 6, 11 and 15 - they all had 'Lesson 01' in the title, but it should have been Lesson 02 for slide 6, Lesson 03 for slide 11, Lesson 04 for slide 15

**Comment by ctesta-oneillmsft** [comment]
resolved with the content in source control
