### ISSUE TITLE
Module 0 - Lab environment setup - Exercise 1 Task 3 Point 4

### ISSUE THREAD

**Issue by annav88** [ctesta-oneillmsft/xyz#5]
# Module: 0
#### Step: 4

Description of issue

When preparing the environment and cloning the dp203 folder into my VM, I get the error shown on the screenshot. Error says RemoteException.
The clone process eventually goes through so might not be critical issue, this is displayed at the second screenshot **lab1_ex1_task3_point4_002.png**

Repro steps:

1. Open the Powershell in the lab environment
2. Go to exercise 1 task 3, 4th point
3. Use the command **git clone https://github.com/ctesta-oneillmsft/xyz.git data-engineering-ilt-deploymen**t in the lab environment
![lab1_ex1_task3_point4_002](https://user-images.githubusercontent.com/83666021/124482254-61813000-dda9-11eb-9cb2-260244629c4d.png)
![lab1_ex1_task3_point4](https://user-images.githubusercontent.com/83666021/124482258-6219c680-dda9-11eb-8a6c-90af42deba1f.png)

**Comment by ctesta-oneillmsft** [comment]
PLease run the steps in Powershell in Administrator mode, not the Powershell ISE. Does it work?

**Comment by annav88** [comment]
Indeed, the copy goes without errors from the PS Admin mode. Thanks Chris!
