### ISSUE TITLE
Module 0 - Lab environment setup - Exercise 2 - Task 1 - Step 9

### ISSUE THREAD

**Issue by annav88** [ctesta-oneillmsft/xyz#6]
# Module: 00
#### Step: 9

Description of issue

When running the Powershell script to setup the environment, I get an error related to the method used in the PowerShell script -  **Get-AzSubscription method is configured for use by Azure Active Directory users only**.

Repro steps:

1. Follow the steps in the exercise and in the 9th step I had the error
2. In the lab environment Powershell environment run .\01-environment-setup.ps1
![lab1_ex2_task1_point9](https://user-images.githubusercontent.com/83666021/124485685-1ec15700-ddad-11eb-92fe-ff84d450a6cf.png)

**Comment by ctesta-oneillmsft** [comment]
please run in PowerShell in Administrator mode, not PowerShell ISE

**Comment by annav88** [comment]
Thanks a lot for the tip, seems not to work. I will double check all the steps again to be sure that there is no mistake coming from my side.
![lab0_ex2_task1_point9_003](https://user-images.githubusercontent.com/83666021/124493694-3a7d2b00-ddb6-11eb-9d73-346c981d9358.png)

**Comment by ctesta-oneillmsft** [comment]
Just need to confirm that you have run Connect-AzAccount and authenticated successfully with the account

And that az login has been run?

Are you also running this in the LODS VM? or your own laptop?

**Comment by annav88** [comment]
Im running it on the LODS VM.

I fixed it. So the reason was that I had two Pass Azure subscriptions, one of which was an old and inactive one. So had to fix it using the below commands : 

**
Clear-AzContext
Connect-AzAccount
Get-AzSubscription
Select-AzSubscription -Subscription subscription_ID
Set-AzContext -Tenant tenant_ID -Subscription subscription_ID
**

P.S. not sure if we need to add a mention in the instructions on the fact that if the student already has an old Azure Pass subscription, they would need to :
1. set the context in Powershell using the above commands
2. at the moment of the execution of the powershell script **.\01-environement-setup.ps1** they would need to choose the right subscription - hence it is better to rename the new subscription beforehand from the portal, because if the subscription names are the same, it might end up selecting the old **Azure Pass - Sponsorship** subscription and not executing the script

Putting below a link on the Azure Context setup in Powershell in case if we want to add them to the instructions : 

https://docs.microsoft.com/fr-fr/powershell/azure/context-persistence?view=azps-6.1.0

![lab0_ex2_task1_point9_004](https://user-images.githubusercontent.com/83666021/124571172-d86d0600-de47-11eb-8af7-cb2d834e33c3.png)

Thanks a lot for your help and quick feedbacks! We can close this issue now
