### ISSUE TITLE
Module 0 - Lab environment setup - Exercise 2 Task 2 Point 4

### ISSUE THREAD

**Issue by annav88** [ctesta-oneillmsft/xyz#7]
# Module: 0 - Lab environment setup with a pre-installed virtual machine
#### Step: 4 - Select Create Cluster to add a new cluster.

**Description of issue**

The Databricks Cluster creation screenshot does not correspond to the list of available versions of Databricks Runtime, both in Github instructions and in the LODS instructions.

Please see the screenshot demonstrating the fact that the Databricks Runtime 7.4 does not exist in the list, so I created the cluster with the same versions of Scala and Spark, but not Dbriccks Runtime.

![lab0_ex2_task2_point4_create_cluster_runtime_7_4_doesnt_exist_anymore](https://user-images.githubusercontent.com/83666021/124575388-a8276680-de4b-11eb-84e5-9b392185e036.png)

Please see attached a screenshot that you could use to replace the one in the Github instructions if needed.

![lab0_ex2_task2_point4_new](https://user-images.githubusercontent.com/83666021/124574967-4666fc80-de4b-11eb-9bf0-5fb68ac6cfc1.png)

Thank you!
Anna

**Comment by ctesta-oneillmsft** [comment]
There will be discrepancies with screenshots like this, The instruction is to select scala 2.12, so this image will suffice
