### ISSUE TITLE
Module 2 - Run interactive queries using serverless SQL pools - Little typo in the Outline

### ISSUE THREAD

**Issue by annav88** [ctesta-oneillmsft/xyz#8]
# Module: 2 - Run interactive queries using serverless SQL pools
#### Step: 0

Description of issue

In the list of exercises for module 2's intro there is a little typo - it says Module 4 instead of Module 2 (in the old version of DP203 it was Module 4).

Please see the screenshot below.

![lab2_overview_typo](https://user-images.githubusercontent.com/83666021/124620859-184ce100-de7a-11eb-8723-6152dfcbcb86.png)

Thank you!
Anna

**Comment by ctesta-oneillmsft** [comment]
resolved
