### ISSUE TITLE
Setup Databricks

### ISSUE THREAD

**Issue by GraemeMalcolm** [ctesta-oneillmsft/xyz#9]
# Module: 00

In instructions to create Databricks cluster:

- We should add an instruction to terminate cluster after creation

**Comment by vasuja515** [comment]
When Spot Instance is checked in regions east us, east us 2, cluster does not turn on.

**Comment by GraemeMalcolm** [comment]
I can't see that option - does it only appear in those regions? (or am I just missing it?)

**Comment by ctesta-oneillmsft** [comment]
resolved the termination statement
